### ISSUE TITLE
Bug in parsing 100

### ISSUE THREAD

**Issue by ajcarr** [onetrueawk/awk#78] opened 2020-04-16 21:04 UTC
[Bug.zip](https://github.com/onetrueawk/awk/files/4489730/Bug.zip)

I recently encountered a bug in both the 20070501 (standard on macOS 10.15 Catalina) and 20180827 (installed using Homebrew) when using an AWK script to convert percentage marks into grades for students, where a 100% mark generates a G- grade (source code, sample input (sample.txt) and sample output (*.tsv) in attached archive, Bug.zip). The problem also manifests with mawk and bioawk, and gawk is the only AWK implementation that performs correctly.

$ cd Bug
$ ./converttogrades-2-awk-20070501.awk < sample.txt > sample-awk-20070501.tsv
$ ./converttogrades-2.awk < sample.txt > sample-awk.tsv # awk 20180827 installed using Homebrew
$ ./converttogrades-2-gawk.awk < sample.txt > sample-gawk.tsv # installed using Homebrew; conflicts with current awk, so only one can be active at at time
$ ./converttogrades-2-mawk.awk < sample.txt > sample-mawk.tsv
$ ./converttogrades-2-bioawk.awk < sample.txt > sample-bioawk.tsv

sample.txt:

Student ID	 Student Name	 Registration Status	 LAB_REP:377237	 EXAM:377238	 Final Grade
12345678	"Poole, Frank"	**Web Registered**		74	74
12345679	"Bowman, Dave"	**Web Registered**		100	100
12345670	"9000, HAL"	**Registered**		69	69

Incorrect .tsv output from all of the above awks except gawk:

Student ID	 Student Name	 Registration Status	 LAB_REP:377237	 EXAM:377238	 Final Grade
12345678	Poole, Frank	**Web Registered**	74	A-
12345679	Bowman, Dave	**Web Registered**	100	G-
12345670	9000, HAL	**Registered**	69	B+

Correct .tsv output from gawk:

Student ID	 Student Name	 Registration Status	 LAB_REP:377237	 EXAM:377238	 Final Grade
12345678	"Poole, Frank"	**Web Registered**		74	A-
12345679	"Bowman, Dave"	**Web Registered**		100	A+
12345670	"9000, HAL"	**Registered**		69	B+

**Comment by awkfan77** [comment] 2020-04-17 11:07
This is not a bug in awk, it's because sample.txt has DOS/Windows line ending.

**Comment by arnoldrobbins** [comment] 2020-04-17 11:14
@awkfan77 Very good catch!  Indeed, removing the carriage returns from the file causes the program to work correctly.

@ajcarr Never heard of bioawk, what is that?

In any case, closing this issue. Thanks.

**Closed by arnoldrobbins** 2020-04-17 11:14 UTC

**Comment by arnoldrobbins** [comment] 2020-06-12 11:32
I have fixed this issue. The updated code is now in the repo. Thanks!
