### ISSUE TITLE
Empty FS problem

### ISSUE THREAD

**Issue by aksr** [onetrueawk/awk#49] opened 2019-10-10 16:17 UTC
This version of awk has the same bug as plan9 version.
More info: https://github.com/9fans/plan9port/pull/292

**Comment by arnoldrobbins** [comment] 2019-10-13 15:37
Thanks for the report.

Technically, for this version, it's not a bug, as this version does not support UTF-8 or any other wide character set encoding.

Adding such support is involved and unlikely to happen. Speaking from experience, it's a lot of work. In addition, the regex routines this awk uses have no such support and are a swamp I don't want to try to navigate through.

So, sorry. I'm closing this issue.

**Closed by arnoldrobbins** 2019-10-13 15:37 UTC

**Comment by aksr** [comment] 2019-10-13 18:20
I wanted to check.., even though I guessed the same.
